Description: IT - networking
Parameters:
  CidrBlock:
    Type: String
    Description: VPC CIDR block
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: Name
          Value: Example VPC
Outputs:
  MyVpcId:
    Description: VPC id
    Value: !Ref VPC
