#
# Disable service control policies
#

tagPolicies:
  my-tag-policy:
    description: My tag policy

organizationalUnits:
  Root:
    accounts:
      - id: "{{ env.TKM_ORG_A_MASTER_ACCOUNT_ID }}"
        description: master
  Root/test-accounts:
    tagPolicies: my-tag-policy
    accounts:
      - "{{ env.TKM_ORG_A_ACCOUNT_1_ID }}"
      - "{{ env.TKM_ORG_A_ACCOUNT_2_ID }}"
      - "{{ env.TKM_ORG_A_ACCOUNT_3_ID }}"
  "Root/sandbox accounts/sandbox-1": {}
  "Root/sandbox accounts/sandbox-2":
    accounts:
      - "{{ env.TKM_ORG_A_ACCOUNT_4_ID }}"
      - "{{ env.TKM_ORG_A_ACCOUNT_5_ID }}"
